# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  name: syntax practise
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - name: Run markdown lint
      run: echo "yaml syntax sucks"
